-- ─────────────────────────────────────────────────────────────────────────────
-- seed_products.sql — NOT THE SOURCE OF TRUTH
-- ─────────────────────────────────────────────────────────────────────────────
-- The real 42-product catalog is managed by the data_ops pipeline.
--
-- Source of truth : scripts/data_ops/lib/products.mjs
-- Full plan       : Possah_Data_Operations_Plan.md
--
-- Pipeline run order:
--   node scripts/data_ops/00_audit.mjs             # backup first — always
--   node scripts/data_ops/01_verify_categories.mjs
--   node scripts/data_ops/02_clean.mjs             # POINT OF NO RETURN
--   node scripts/data_ops/03_upload_images.mjs
--   node scripts/data_ops/04_seed_products.mjs
--   node scripts/data_ops/05_seed_orders.mjs
--   node scripts/data_ops/06_verify.mjs
--   node scripts/data_ops/99_restore.mjs           # rollback if needed
--
-- DO NOT add SQL product inserts here — they will conflict with the pipeline.
-- ─────────────────────────────────────────────────────────────────────────────
